---
# tasks file for aws_create_dns_records
- name: Create DNS record
  amazon.aws.route53:
    state: present
    hosted_zone_id: Z0616275232MR8FXRWUIA
    record: test1-ansible-tower-test.com
    type: TXT
    value: this is a test
