---
# tasks file for aws_create_dns_records
- name: Create DNS record
  amazon.aws.route53:
    state: present
    hosted_zone_id: Z0616275232MR8FXRWUIA
    record: ansible-tower-test.com
    type: TXT
    ttl: 7200
    value: "this is a test11"
