---
# tasks file for aws_create_dns_records
- name: create DNS records - for vanity URL
  amazon.aws.route53:
    state: present
    zone: "{{ route53_zone_id }}"
    record: "{{ item.name }}"
    type: "{{ item.type }}"
    ttl: "{{ item.ttl }}"
    value: "{{ item.value }}"
    wait: true
  loop: "{{ dns_records }}"